/**
 * `usedesign gen openapi` — derive an API contract from the cards. The opposite direction to
 * `scaffold`: there the application's own OpenAPI seeds draft cards; here the cards themselves
 * produce an OpenAPI document. The point is the contract-first flow the format was conceived
 * for — a `conceived` or `designed` card yields its API contract BEFORE any code exists, and
 * the same card later becomes the drift guard for the code that implements it.
 *
 * The machine emits only what cards actually know: method, path, response codes (named by the
 * outcomes and violated steps that declare them), path parameters, title, maturity. Nothing is
 * invented — an OpenAPI field the cards cannot source is absent, not defaulted.
 *
 * TypeScript-only, like `scaffold`, and recorded as such: generation is tooling around the
 * format, not part of it — the conformance corpus binds the validators and the checks, which
 * is where dialects would hurt.
 */
import { writeFileSync } from "node:fs";
import { Config, Finding, loadCardFiles } from "./core.js";

interface GenCounts {
  cards: number;
  rest: number;
  routes: number;
  merged: string[];
}

/** Names a card gives to a status code: outcomes and violated steps that answer with it. */
function namesFor(card: Record<string, any>, code: number): string[] {
  const names: string[] = [];
  for (const outcome of card["outcomes"] ?? []) {
    if (outcome?.http === code && outcome?.id) names.push(String(outcome.id));
  }
  for (const step of card["steps"] ?? []) {
    if (step?.on_violation?.http === code && step?.on_violation?.error) names.push(String(step.on_violation.error));
  }
  return names;
}

/** `{param}` segments of the path — the only parameter source a card is guaranteed to carry. */
function pathParameters(path: string): any[] {
  const params: any[] = [];
  for (const match of path.matchAll(/\{([^}]+)\}/g)) {
    params.push({ name: match[1], in: "path", required: true, schema: { type: "string" } });
  }
  return params;
}

export function buildOpenApi(config: Config, base: string): { doc: any; counts: GenCounts; findings: Finding[] } {
  const { cards, findings } = loadCardFiles(config, base);
  const paths: Record<string, any> = {};
  const merged: string[] = [];
  let rest = 0;

  for (const [id, card] of [...cards].sort(([a], [b]) => a.localeCompare(b))) {
    for (const iface of Object.values<any>(card["interfaces"] ?? {})) {
      if (iface?.transport !== "http_rest" || !iface.method || !iface.path) continue;
      rest += 1;
      const method = String(iface.method).toLowerCase();
      const route = (paths[String(iface.path)] ??= {});
      const declared: number[] = iface.responses ?? [];

      if (route[method]) {
        // Two cards on one route — the dispatch idiom (one path, several operations told apart
        // by the body). One OpenAPI operation, both cards named; responses are the union.
        const operation = route[method];
        operation["x-usedesign-operations"].push(id);
        merged.push(`${String(iface.method).toUpperCase()} ${iface.path} ← ${operation["x-usedesign-operations"].join(", ")}`);
        for (const code of declared) {
          const existing = operation.responses[String(code)];
          const names = namesFor(card, code);
          if (!existing) operation.responses[String(code)] = { description: names.join(", ") || "declared by the card" };
          else if (names.length) {
            const parts = [...existing.description.split(", "), ...names].filter((s: string) => s && s !== "declared by the card");
            existing.description = [...new Set(parts)].join(", ");
          }
        }
        continue;
      }

      const responses: Record<string, any> = {};
      for (const code of declared) {
        responses[String(code)] = { description: namesFor(card, code).join(", ") || "declared by the card" };
      }
      route[method] = {
        operationId: id,
        summary: card["title"] ?? id,
        "x-usedesign-operations": [id],
        "x-usedesign-maturity": card["maturity"] ?? "",
        ...(pathParameters(String(iface.path)).length ? { parameters: pathParameters(String(iface.path)) } : {}),
        responses,
      };
    }
  }

  // Deterministic output: sorted paths, no timestamps — a regenerated document that did not
  // change must be byte-identical, or every run manufactures a junk diff.
  const sortedPaths: Record<string, any> = {};
  for (const key of Object.keys(paths).sort()) sortedPaths[key] = paths[key];

  const routes = Object.values(sortedPaths).reduce((n: number, methods: any) => n + Object.keys(methods).length, 0);
  const doc = {
    openapi: "3.0.3",
    info: {
      title: "API contract derived from Operation Cards",
      description:
        "Generated by `usedesign gen openapi`. The cards are the source; a field the cards cannot source is absent, not defaulted.",
      version: "0.0.0+cards",
    },
    paths: sortedPaths,
  };
  return { doc, counts: { cards: cards.length, rest, routes, merged }, findings };
}

export function commandGen(
  configPath: string,
  outPath: string,
  loadConfig: (p: string) => { config: Config; base: string },
): number {
  const { config, base } = loadConfig(configPath);
  const { doc, counts, findings } = buildOpenApi(config, base);
  for (const finding of findings) console.log(`  ${finding.severity === "error" ? "ERROR  " : "warning"}  ${finding}`);
  if (counts.routes === 0) {
    console.error("usedesign gen: the cards declare no REST interface — nothing to derive");
    return 1;
  }
  writeFileSync(outPath, JSON.stringify(doc, null, 2) + "\n", "utf8");
  console.log(`cards:      ${counts.cards} read, ${counts.rest} REST interface(s)`);
  console.log(`routes:     ${counts.routes} path+method pair(s) → ${outPath}`);
  for (const note of counts.merged) console.log(`merged:     ${note}`);
  return 0;
}
